In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [4]:
x3.ndim

3

In [5]:
x3.size

60

In [6]:
x3.shape

(3, 4, 5)

In [7]:
x3.dtype

dtype('int64')

In [8]:
x3.itemsize

8

In [9]:
x=np.arange(10)

In [10]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[-1:]

array([9])

In [14]:
x[-1:0:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [15]:
x4 = x3

In [16]:
x4

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [17]:
x4[0,0,0] = 0

In [18]:
x4

array([[[0, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [19]:
x3

array([[[0, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [20]:
x5=[]

In [21]:
x5=x3.copy()

In [22]:
x5[0,0,0] = 2

In [23]:
x5, x3

(array([[[2, 1, 5, 9, 8],
         [9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7]],
 
        [[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]],
 
        [[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]]]), array([[[0, 1, 5, 9, 8],
         [9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7]],
 
        [[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]],
 
        [[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]]]))

In [24]:
locals()

{'In': ['',
  u'import numpy as np',
  u'np.random.seed(0)',
  u'x1 = np.random.randint(10, size=6)\nx2 = np.random.randint(10, size=(3, 4))\nx3 = np.random.randint(10, size=(3, 4, 5))',
  u'x3.ndim',
  u'x3.size',
  u'x3.shape',
  u'x3.dtype',
  u'x3.itemsize',
  u'x=np.arange(10)',
  u'x',
  u'x[2:]',
  u'x[-1:]',
  u'x[-1:0]',
  u'x[-1:0:-1]',
  u'x4 = x3',
  u'x4',
  u'x4[0,0,0] = 0',
  u'x4',
  u'x3',
  u'x5=[]',
  u'x5=x3.copy()',
  u'x5[0,0,0] = 2',
  u'x5, x3',
  u'locals()'],
 'Out': {4: 3,
  5: 60,
  6: (3, 4, 5),
  7: dtype('int64'),
  8: 8,
  10: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
  11: array([2, 3, 4, 5, 6, 7, 8, 9]),
  12: array([9]),
  13: array([], dtype=int64),
  14: array([9, 8, 7, 6, 5, 4, 3, 2, 1]),
  16: array([[[0, 1, 5, 9, 8],
          [9, 4, 3, 0, 3],
          [5, 0, 2, 3, 8],
          [1, 3, 3, 3, 7]],
  
         [[0, 1, 9, 9, 0],
          [4, 7, 3, 2, 7],
          [2, 0, 0, 4, 5],
          [5, 6, 8, 4, 1]],
  
         [[4, 9, 8, 1, 1],
          [7